# Generated by Django 4.1.1 on 2022-10-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0012_remove_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspaper.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='date_news',
            field=models.CharField(default='', max_length=16),
        ),
    ]
