# Generated by Django 4.1.1 on 2022-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_remove_category_url_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_news',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
