# Generated by Django 4.1.1 on 2022-10-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0014_alter_article_date_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_news',
            new_name='da_news',
        ),
    ]
