# Generated by Django 4.1.1 on 2022-10-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='newspaper.image'),
        ),
    ]
