# Generated by Django 4.1.1 on 2022-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_comment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
