# Generated by Django 4.1.1 on 2022-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_remove_category_url_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_news',
            field=models.DateTimeField(null=True),
        ),
    ]
