# Generated by Django 4.1.1 on 2022-10-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0012_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
