# Generated by Django 4.1.1 on 2022-10-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_comemnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='comemnt',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspaper.article'),
        ),
    ]
