# Generated by Django 4.1.1 on 2022-10-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0014_comemnt_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comemnt',
            new_name='Comment',
        ),
    ]
