# Generated by Django 4.1.1 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_remove_article_categories_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='article', to='newspaper.category'),
        ),
    ]
