# Generated by Django 4.1.1 on 2022-10-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_category_article_date_news_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
