# Generated by Django 4.1.1 on 2022-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0011_author_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
