# Generated by Django 4.1.1 on 2022-10-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0016_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
